### PR TITLE
Implement show_vlans() and show_mac_address_table()

### PR DESCRIPTION
**Pull request by danimo**
Each was reformatted with black.

### CODE REVIEW

**Comment by danimo** [comment]
I see that contrary to the claims, there _are_ tests. So I shall add my preliminary ones (that are not using the framework). Feel free to delay the merge until I have time to add them (probably tonight).

**Comment by ggiesen** [comment]
> 
> 
> I see that contrary to the claims, there _are_ tests. So I shall add my preliminary ones (that are not using the framework). Feel free to delay the merge until I have time to add them (probably tonight).

Yes I just added them yesterday (your pull request caught me by surprise after just publishing the repo on 2020-06-10. I'll take care of the tests for these two getters. I've also created a new branch 'develop' to merge request into, and once I'm confident it's working well I'll push to master

**Comment by danimo** [comment]
> Yes I just added them yesterday (your pull request caught me by surprise after just publishing the repo on 2020-06-10. I'll take care of the tests for these two getters. I've also created a new branch 'develop' to merge request into, and once I'm confident it's working well I'll push to master

Sorry not sorry ;). I just noticed those were missing. And for some reason, netbox fails to list LLDP neighbors, but that's probably a timeout issue, and system information. I'll be looking into that later.

**Comment by danimo** [comment]
Oh and thanks for taking care of the tests. Open Source at its best!

**Comment by ggiesen** [comment]
Tests are implemented and I have merged to master. I had to make a few changes to the output format for get_mac_address_table as you were spitting out VLANs in MAC format, and I pruned unconfigured LAGs from get_vlans. I've merged all the changes to master. Thanks for the contribution. Let me know if you still have issues with LLDP neighbors and I'll test from this side.

**Comment by ggiesen** [comment]
And for some reason, netbox fails to list LLDP neighbors, but that's probably a timeout issue, and system information. I'll be looking into that later.

System information definitely works for me. LLDP neighbors was broken because I was outputting the short interface names, not the canonical interface names. The latest master has that fixed.

**Pull request merged**
